<?php
/** @var Onecode\ShopFlixConnector\Block\Adminhtml\ReturnOrder\Items\Column\DefaultColumn $block
 */
?>
<?php if ($item = $block->getItem()) : ?>
    <table class="qty-table">
        <tr>
            <th><strong><?= $block->escapeHtml(__('Returned')); ?>: <?= (float)$item->getQty()?></strong></th>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('In Stock')); ?></th>
        </tr>
        <?php foreach ($item->getRealQty() as $sources) : ?>
            <tr>
                <td>
                    <strong><?= $sources['stock_name'] . ": " . $sources['qty'] ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
