<?php
use Onecode\ShopFlixConnector\Block\Adminhtml\Items\Renderer\DefaultRenderer;

?>
<?php /** @var $block DefaultRenderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
<td class="col-price">
    <?= $block->getColumnHtml($_item, 'price') ?>
</td>
<td class="col-qty"><?= $block->getColumnHtml($_item, 'qty') ?></td>
<td class="col-discount"><?= /* @noEscape */
    $block->displayPriceAttribute('discount_amount') ?></td>
<td class="col-total last">
    <?= $block->getColumnHtml($_item, 'total') ?>
</td>
