<?php
/** @var Onecode\ShopFlixConnector\Block\Adminhtml\Items\Column\DefaultColumn $block
 */

use Onecode\ShopFlixConnector\Api\Data\OrderInterface;

?>


<?php if ($item = $block->getItem()) : ?>
    <table class="qty-table">
        <tr <?php if ($block->getOrder()->getState() == OrderInterface::STATE_PENDING_ACCEPTANCE): ?> style="color:<?= $item->isOrderedQtyLower() ? "green" : "red" ?>;"<?php endif ?>>
            <th><strong><?= $block->escapeHtml(__('Ordered')); ?></strong></th>
            <td><strong><?= (float)$item->getQty() ?></strong>
            </td>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('In Stock')); ?></th>
        </tr>
        <?php foreach ($item->getRealQty() as $sources) : ?>
            <tr>
                <td>
                    <strong><?= $sources['stock_name'] . ": " . $sources['qty'] ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
